apiVersion: v1
kind: Service
metadata:
  name: redis # this is important because other services depend on this name
  labels:
    name: redis-service # this also
    app: demo-voting-app
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-pod
    app: demo-voting-app