apiVersion: v1
kind: Service
metadata:
  name: voting-service # this is important because other services depend on this name
  labels:
    name: voting-service  # this also
    app: demo-voting-app
spec:
  type: NodePort # this is important because we need to access the service from outside the cluster, othewise this will be of type ClusterIP
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    name: voting-app-pod
    app: demo-voting-app